export const REASON_CODE = {
// System / mode / config
WATCHER_DISABLED: "WATCHER_DISABLED",
EMERGENCY_STOP_ACTIVE: "EMERGENCY_STOP_ACTIVE",
INVALID_EXECUTION_MODE: "INVALID_EXECUTION_MODE",
INVALID_TOKEN_SNAPSHOT: "INVALID_TOKEN_SNAPSHOT",
INVALID_POSITION_STATE: "INVALID_POSITION_STATE",
SETTINGS_PATCH_APPLIED: "SETTINGS_PATCH_APPLIED",
SENTINEL_MODE_CHANGED: "SENTINEL_MODE_CHANGED",
SENTINEL_EMERGENCY_STOP: "SENTINEL_EMERGENCY_STOP",

// Hard rejects
TRANSFER_RESTRICTION_RISK: "TRANSFER_RESTRICTION_RISK",
HONEYPOT_RISK: "HONEYPOT_RISK",
LIQUIDITY_BREAK_RISK: "LIQUIDITY_BREAK_RISK",
SPOOFED_VOLUME_RISK: "SPOOFED_VOLUME_RISK",
LOW_LIQUIDITY: "LOW_LIQUIDITY",
WIDE_SPREAD: "WIDE_SPREAD",
HIGH_PRICE_IMPACT: "HIGH_PRICE_IMPACT",
TOP_HOLDER_TOO_CONCENTRATED: "TOP_HOLDER_TOO_CONCENTRATED",
TOP5_TOO_CONCENTRATED: "TOP5_TOO_CONCENTRATED",
HIDDEN_CONTROL_TOO_HIGH: "HIDDEN_CONTROL_TOO_HIGH",
CONTAMINATION_TOO_HIGH: "CONTAMINATION_TOO_HIGH",
COORDINATION_RISK_TOO_HIGH: "COORDINATION_RISK_TOO_HIGH",

// Operator gate
OPERATOR_QUALITY_TOO_LOW: "OPERATOR_QUALITY_TOO_LOW",
INSIDER_SELL_RISK_TOO_HIGH: "INSIDER_SELL_RISK_TOO_HIGH",
OPERATOR_CLUSTER_LIMIT_REACHED: "OPERATOR_CLUSTER_LIMIT_REACHED",

// Regime gate
RISK_OFF_REGIME: "RISK_OFF_REGIME",
REGIME_SCORE_TOO_LOW: "REGIME_SCORE_TOO_LOW",
MARKET_QUALITY_TOO_LOW: "MARKET_QUALITY_TOO_LOW",

// Scout entry gating
SCOUT_DISABLED: "SCOUT_DISABLED",
POSITION_ALREADY_OPEN: "POSITION_ALREADY_OPEN",
TOKEN_IN_COOLDOWN: "TOKEN_IN_COOLDOWN",
DAILY_LOSS_LIMIT_HIT: "DAILY_LOSS_LIMIT_HIT",
DAILY_SCOUT_BUDGET_HIT: "DAILY_SCOUT_BUDGET_HIT",
MAX_OPEN_POSITIONS_HIT: "MAX_OPEN_POSITIONS_HIT",
MAX_TOKENS_PER_HOUR_HIT: "MAX_TOKENS_PER_HOUR_HIT",
SELLER_EXHAUSTION_NOT_STRONG_ENOUGH: "SELLER_EXHAUSTION_NOT_STRONG_ENOUGH",
RECLAIM_TOO_WEAK: "RECLAIM_TOO_WEAK",
BUY_PRESSURE_TOO_WEAK: "BUY_PRESSURE_TOO_WEAK",
PERSISTENCE_TOO_WEAK: "PERSISTENCE_TOO_WEAK",
STRUCTURE_NOT_READY: "STRUCTURE_NOT_READY",
SCOUT_ENTRY_APPROVED: "SCOUT_ENTRY_APPROVED",

// Sniper add gating
SNIPER_DISABLED: "SNIPER_DISABLED",
NO_VALID_SCOUT_POSITION: "NO_VALID_SCOUT_POSITION",
DAILY_SNIPER_BUDGET_HIT: "DAILY_SNIPER_BUDGET_HIT",
MAX_POSITION_SIZE_EXCEEDED: "MAX_POSITION_SIZE_EXCEEDED",
RECLAIM_NOT_CONFIRMED: "RECLAIM_NOT_CONFIRMED",
BUY_PRESSURE_NOT_PERSISTENT: "BUY_PRESSURE_NOT_PERSISTENT",
PERSISTENCE_NOT_STRONG_ENOUGH: "PERSISTENCE_NOT_STRONG_ENOUGH",
STRUCTURE_NOT_HEALTHY_ENOUGH: "STRUCTURE_NOT_HEALTHY_ENOUGH",
TOO_EXTENDED_FOR_ADD: "TOO_EXTENDED_FOR_ADD",
LIQUIDITY_DECAY_TOO_HIGH: "LIQUIDITY_DECAY_TOO_HIGH",
SNIPER_ADD_APPROVED: "SNIPER_ADD_APPROVED",

// Early exits / invalidations
EARLY_RECLAIM_FAILED: "EARLY_RECLAIM_FAILED",
WEAK_STALL_NO_BUYERS: "WEAK_STALL_NO_BUYERS",
INSIDER_DUMP_DETECTED: "INSIDER_DUMP_DETECTED",
LIQUIDITY_BREAK_DETECTED: "LIQUIDITY_BREAK_DETECTED",
STRUCTURAL_HEALTH_COLLAPSED: "STRUCTURAL_HEALTH_COLLAPSED",
INVALIDATION_EXIT: "INVALIDATION_EXIT",

// Profit taking
AUTO_BANK_DISABLED: "AUTO_BANK_DISABLED",
TEN_X_NOT_REACHED: "TEN_X_NOT_REACHED",
TEN_X_REACHED: "TEN_X_REACHED",
ALREADY_BANKED: "ALREADY_BANKED",
PARTIAL_TAKE_PROFIT_EXECUTED: "PARTIAL_TAKE_PROFIT_EXECUTED",

// Runner management
RUNNER_MANAGEMENT_DISABLED: "RUNNER_MANAGEMENT_DISABLED",
NO_RUNNER_POSITION: "NO_RUNNER_POSITION",
RUNNER_HEALTHY: "RUNNER_HEALTHY",
BUY_PRESSURE_DECAY: "BUY_PRESSURE_DECAY",
PERSISTENCE_DECAY: "PERSISTENCE_DECAY",
STRUCTURAL_HEALTH_WEAK: "STRUCTURAL_HEALTH_WEAK",
FAILED_BREAKOUTS_TOO_MANY: "FAILED_BREAKOUTS_TOO_MANY",
RUNNER_INSIDER_SELL_RISK: "RUNNER_INSIDER_SELL_RISK",
RUNNER_LIQUIDITY_DECAY: "RUNNER_LIQUIDITY_DECAY",
RUNNER_EXIT_EXECUTED: "RUNNER_EXIT_EXECUTED",

// Kill switch / daily safety
DAILY_LOSS_LIMIT: "DAILY_LOSS_LIMIT",
CONSECUTIVE_FAILURE_LIMIT: "CONSECUTIVE_FAILURE_LIMIT",
RUG_RATE_TOO_HIGH: "RUG_RATE_TOO_HIGH",
RECLAIM_SUCCESS_TOO_LOW: "RECLAIM_SUCCESS_TOO_LOW",
MARKET_LIQUIDITY_TOO_LOW: "MARKET_LIQUIDITY_TOO_LOW",
KILL_SWITCH_TRIGGERED: "KILL_SWITCH_TRIGGERED",

// Generic decisions
TOKEN_REJECTED: "TOKEN_REJECTED",
WATCHLIST_ONLY: "WATCHLIST_ONLY",
HOLD_POSITION: "HOLD_POSITION",
FULL_EXIT_EXECUTED: "FULL_EXIT_EXECUTED",
POSITION_CLOSED: "POSITION_CLOSED",
};

export const REASON_CODE_GROUPS = {
SYSTEM: [
REASON_CODE.WATCHER_DISABLED,
REASON_CODE.EMERGENCY_STOP_ACTIVE,
REASON_CODE.INVALID_EXECUTION_MODE,
REASON_CODE.INVALID_TOKEN_SNAPSHOT,
REASON_CODE.INVALID_POSITION_STATE,
REASON_CODE.SETTINGS_PATCH_APPLIED,
REASON_CODE.SENTINEL_MODE_CHANGED,
REASON_CODE.SENTINEL_EMERGENCY_STOP,
],

HARD_REJECT: [
REASON_CODE.TRANSFER_RESTRICTION_RISK,
REASON_CODE.HONEYPOT_RISK,
REASON_CODE.LIQUIDITY_BREAK_RISK,
REASON_CODE.SPOOFED_VOLUME_RISK,
REASON_CODE.LOW_LIQUIDITY,
REASON_CODE.WIDE_SPREAD,
REASON_CODE.HIGH_PRICE_IMPACT,
REASON_CODE.TOP_HOLDER_TOO_CONCENTRATED,
REASON_CODE.TOP5_TOO_CONCENTRATED,
REASON_CODE.HIDDEN_CONTROL_TOO_HIGH,
REASON_CODE.CONTAMINATION_TOO_HIGH,
REASON_CODE.COORDINATION_RISK_TOO_HIGH,
],

OPERATOR_GATE: [
REASON_CODE.OPERATOR_QUALITY_TOO_LOW,
REASON_CODE.INSIDER_SELL_RISK_TOO_HIGH,
REASON_CODE.OPERATOR_CLUSTER_LIMIT_REACHED,
],

REGIME_GATE: [
REASON_CODE.RISK_OFF_REGIME,
REASON_CODE.REGIME_SCORE_TOO_LOW,
REASON_CODE.MARKET_QUALITY_TOO_LOW,
],

SCOUT: [
REASON_CODE.SCOUT_DISABLED,
REASON_CODE.POSITION_ALREADY_OPEN,
REASON_CODE.TOKEN_IN_COOLDOWN,
REASON_CODE.DAILY_LOSS_LIMIT_HIT,
REASON_CODE.DAILY_SCOUT_BUDGET_HIT,
REASON_CODE.MAX_OPEN_POSITIONS_HIT,
REASON_CODE.MAX_TOKENS_PER_HOUR_HIT,
REASON_CODE.SELLER_EXHAUSTION_NOT_STRONG_ENOUGH,
REASON_CODE.RECLAIM_TOO_WEAK,
REASON_CODE.BUY_PRESSURE_TOO_WEAK,
REASON_CODE.PERSISTENCE_TOO_WEAK,
REASON_CODE.STRUCTURE_NOT_READY,
REASON_CODE.SCOUT_ENTRY_APPROVED,
],

SNIPER: [
REASON_CODE.SNIPER_DISABLED,
REASON_CODE.NO_VALID_SCOUT_POSITION,
REASON_CODE.DAILY_SNIPER_BUDGET_HIT,
REASON_CODE.MAX_POSITION_SIZE_EXCEEDED,
REASON_CODE.RECLAIM_NOT_CONFIRMED,
REASON_CODE.BUY_PRESSURE_NOT_PERSISTENT,
REASON_CODE.PERSISTENCE_NOT_STRONG_ENOUGH,
REASON_CODE.STRUCTURE_NOT_HEALTHY_ENOUGH,
REASON_CODE.TOO_EXTENDED_FOR_ADD,
REASON_CODE.INSIDER_SELL_RISK_TOO_HIGH,
REASON_CODE.LIQUIDITY_DECAY_TOO_HIGH,
REASON_CODE.SNIPER_ADD_APPROVED,
],

EXITS: [
REASON_CODE.EARLY_RECLAIM_FAILED,
REASON_CODE.WEAK_STALL_NO_BUYERS,
REASON_CODE.INSIDER_DUMP_DETECTED,
REASON_CODE.LIQUIDITY_BREAK_DETECTED,
REASON_CODE.STRUCTURAL_HEALTH_COLLAPSED,
REASON_CODE.INVALIDATION_EXIT,
REASON_CODE.FULL_EXIT_EXECUTED,
REASON_CODE.POSITION_CLOSED,
],

TAKE_PROFIT: [
REASON_CODE.AUTO_BANK_DISABLED,
REASON_CODE.TEN_X_NOT_REACHED,
REASON_CODE.TEN_X_REACHED,
REASON_CODE.ALREADY_BANKED,
REASON_CODE.PARTIAL_TAKE_PROFIT_EXECUTED,
],

RUNNER: [
REASON_CODE.RUNNER_MANAGEMENT_DISABLED,
REASON_CODE.NO_RUNNER_POSITION,
REASON_CODE.RUNNER_HEALTHY,
REASON_CODE.BUY_PRESSURE_DECAY,
REASON_CODE.PERSISTENCE_DECAY,
REASON_CODE.STRUCTURAL_HEALTH_WEAK,
REASON_CODE.FAILED_BREAKOUTS_TOO_MANY,
REASON_CODE.RUNNER_INSIDER_SELL_RISK,
REASON_CODE.RUNNER_LIQUIDITY_DECAY,
REASON_CODE.RUNNER_EXIT_EXECUTED,
],

KILL_SWITCH: [
REASON_CODE.DAILY_LOSS_LIMIT,
REASON_CODE.CONSECUTIVE_FAILURE_LIMIT,
REASON_CODE.RUG_RATE_TOO_HIGH,
REASON_CODE.RECLAIM_SUCCESS_TOO_LOW,
REASON_CODE.MARKET_LIQUIDITY_TOO_LOW,
REASON_CODE.KILL_SWITCH_TRIGGERED,
],

GENERIC: [
REASON_CODE.TOKEN_REJECTED,
REASON_CODE.WATCHLIST_ONLY,
REASON_CODE.HOLD_POSITION,
],
};

export const ALL_REASON_CODES = Object.freeze(Object.values(REASON_CODE));

export function isValidReasonCode(value) {
return ALL_REASON_CODES.includes(String(value ?? "").trim());
}

export function normalizeReasonCodes(input) {
if (!Array.isArray(input)) return [];
return input
.map((value) => String(value ?? "").trim())
.filter((value) => value && isValidReasonCode(value));
}

export function ensureReasonCode(value, fallback = REASON_CODE.WATCHLIST_ONLY) {
return isValidReasonCode(value) ? value : fallback;
}

export function ensureReasonCodeArray(input, fallback = []) {
const normalized = normalizeReasonCodes(input);
if (normalized.length) return normalized;
return normalizeReasonCodes(fallback);
}

export function getReasonCodeGroup(reasonCode) {
const normalized = ensureReasonCode(valueOrFallback(reasonCode), "");
if (!normalized) return null;

for (const [groupName, codes] of Object.entries(REASON_CODE_GROUPS)) {
if (codes.includes(normalized)) return groupName;
}
return null;
}

function valueOrFallback(value, fallback = "") {
const normalized = String(value ?? "").trim();
return normalized || fallback;
}

export default {
REASON_CODE,
REASON_CODE_GROUPS,
ALL_REASON_CODES,
isValidReasonCode,
normalizeReasonCodes,
ensureReasonCode,
ensureReasonCodeArray,
getReasonCodeGroup,
};
