CREATE TABLE IF NOT EXISTS builders (
id INTEGER PRIMARY KEY AUTOINCREMENT,
wallet TEXT UNIQUE NOT NULL,
alias TEXT NOT NULL,
bio TEXT DEFAULT '',
avatar_url TEXT DEFAULT '',
twitter TEXT DEFAULT '',
telegram TEXT DEFAULT '',
show_projects INTEGER NOT NULL DEFAULT 0,
builder_score INTEGER NOT NULL DEFAULT 50,
projects_launched INTEGER NOT NULL DEFAULT 0,
successful_launches INTEGER NOT NULL DEFAULT 0,
created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_builders_wallet ON builders(wallet);
