BEGIN TRANSACTION;

ALTER TABLE launches ADD COLUMN price REAL NOT NULL DEFAULT 0;
ALTER TABLE launches ADD COLUMN market_cap REAL NOT NULL DEFAULT 0;
ALTER TABLE launches ADD COLUMN volume_24h REAL NOT NULL DEFAULT 0;

COMMIT;